#!/usr/bin/env bash

[ -f $(dirname $0)/.env ] && source $(dirname $0)/.env

if [ -z $DEBUG ]; then
    ruby $(dirname $0)/scrape.rb > ${LOGPATH:-/var/log/scrape}/scrape.log 2>&1
else
    ruby --debug $(dirname $0)/scrape.rb --no-slack
fi
