#!/usr/bin/env bash

[ -f $(dirname $0)/.env ] && source $(dirname $0)/.env

if [ ! -z $NOSLACK ]; then
    ARGS="--no-slack"
fi

if [ -z $DEBUG ]; then
    ruby $(dirname $0)/scrape.rb
else
    ruby --debug $(dirname $0)/scrape.rb $ARGS
fi
