#!/usr/bin/env ruby

require "open-uri"
require "nokogiri"

if ARGV.length != 2
  puts "usage: #{File.basename(__FILE__)} <url> <css selector>"
  exit 1
end

resp = URI.open(ARGV[0]) do |f|
  f.read
end

h = Nokogiri::HTML(resp)
puts h.css(ARGV[1])
